# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CapRover

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Deploy to Caprover Using GitHub Actions
        uses: dankore/github-to-caprover@v.1.0.3
        with:
          server: '${{ secrets.CAPROVER_URL }}'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appName: '${{ secrets.CAPROVER_APP }}'
          branch: '${{ github.event.inputs.branch }}'
